Feat/KFS-1045 unset compute pool
confluentinc/cli pull request #2291
Opened 2023-09-21 17:06 UTC by Guttz

Release Notes
-------------

Checklist
---------
1. [CRUCIAL] Is the change for features that are already live in prod?
   * yes: ok
   
What
----

User can now unset a compute pool, so there's no default set

References
----------

Test & Review
-------------

Open Questions / Follow-ups
---------------------------

2023-09-21 17:44 UTC, swist requested changes

2023-09-21 17:44 UTC, swist commented on internal/flink/command_compute_pool_unset.go
> +	output.Printf(errors.UnsetResourceMsg, resource.FlinkComputePool, computePoolToUnset)
Can you add a snapshot test for this too

2023-09-21 19:42 UTC, brianstrauch commented on internal/flink/command_compute_pool.go
> +	cmd.AddCommand(c.newComputePoolUnsetCommand())
Alphabetize!

2023-09-26 16:24 UTC, brianstrauch commented on test/flink_test.go
> +		{args: "flink compute-pool unset", login: "cloud", fixture: "flink/compute-pool/unset_before_use.golden"},
```suggestion
		{args: "flink compute-pool unset", login: "cloud", fixture: "flink/compute-pool/unset-before-use.golden"},
```

2023-10-11 14:36 UTC, Guttz commented
The reason we want this is that now the user has no way of stopping filtering the `confluent flink statement list` response once he set the compute pool once. After setting the compute pool once, he will always get a filtered list of statements.

2023-10-12 19:28 UTC, brianstrauch approved these changes

2023-10-12 19:28 UTC, brianstrauch commented on internal/flink/command_compute_pool_unset.go
> +		Long:  "Unset the current Flink compute pool that was set with `confluent Flink compute-pool use`.",
```suggestion
		Long:  "Unset the current Flink compute pool that was set with `confluent flink compute-pool use`.",
```

2023-10-17 09:43 UTC, merged