Update URL in scripts
confluentinc/cli pull request #2875
Opened 2024-09-09 20:25 UTC by brianstrauch

Release Notes
-------------

Breaking Changes
- PLACEHOLDER

New Features
- PLACEHOLDER

Bug Fixes
- PLACEHOLDER

Checklist
---------
- [ ] Leave this box unchecked if features are not yet available in production

What
----

References
----------

Test & Review
-------------

2024-09-09 20:31 UTC, sgagniere approved these changes

2024-09-09 23:23 UTC, sgagniere requested changes
Looks like the installer is broken

2024-09-10 21:47 UTC, brianstrauch commented on install.sh
> +  NAME=$([ ${ABOVE_4_0} = "true" ] && echo "${BINARY}_${OS}_${ARCH}" || echo "${BINARY}_${VERSION}_${OS}_${ARCH}")
```suggestion
  NAME=$([ ${ABOVE_4_0} = "true" ] && echo "${BINARY}_${OS}_${ARCH}" || echo "${BINARY}_${VERSION}_${OS}_${ARCH}")
  TARBALL=${NAME}.${FORMAT}
```

2024-09-10 21:47 UTC, brianstrauch commented on install.sh
> +  TARBALL_URL=${ARCHIVES_URL}/${NAME}.${FORMAT}
```suggestion
  TARBALL_URL=${ARCHIVES_URL}/${TARBALL}
```

2024-09-10 22:10 UTC, sgagniere approved these changes
thanks!

2024-09-11 16:05 UTC, merged